### PR TITLE
Update udpraw.md

### PR DESCRIPTION
**Pull request by houseofbugs**
Document the limit of LEDs so users are not wasting time trying to figure out why things are not working.

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@houseofbugs Am I right, that this PR is triggered out of a using WLED context?
The limitation is on the receiving side and at the UDP-Raw sending side.
If you would like to connect to WLED, I would suggest making use of the Hyperion WLED-Device.
Besides streaming, it provides a better integration with WLED anyway.

Please confirm that the triggering scenario was WLED. We will then rephrase and document WLED#s limitation at the WLED device and not at UDP-Raw. Here we might add that for WLED integration the WLED device is recommended to be used.

**Comment by houseofbugs** [comment]
It does not work at all when using the native WLED integration in Hyperion and "works" but colors are completely wrong when using UDPraw. I ended up having to split the installation to 2x WLED controllers with 323 leds on each controller to get it working.

**Comment by Lord-Grey** [comment]
OK. You want using WLED, i.e. you confirm the limitation of WLED.

Given that WLED has the limitation of number of supported LEDs by default, the documentation should be with the WLED device.
To overcome WLEDs limitation you could build your own WLED, see below:

Rationale by WLED-Developer Aircoookie: "_Unfortunately the 490 LED is a hard limit. The reason is that the maximum amount of data that can be transmitted via a UDP frame at once is 1472 bytes (and we need 3 bytes data per LED). You could try to increase UDP_IN_MAXSIZE in wled07_notify.ino, maybe the 8266 (or at least ESP32) can handle larger UDP packets by reassembling the frames_"

That your Colors are off with UDPRaw, might be due to a misconfiguration of the RGB-Byte order.

**Comment by houseofbugs** [comment]
> That your Colors are off with UDPRaw, might be due to a misconfiguration of the RGB-Byte order.

This is not the case. IE: Setting it to 400 leds (with UDPRaw) instead of 646 caused them to work correctly and not have issues. Setting it to the full 646 caused random color shifting and artifacting. To be clear, when using the WLED integration with 646 LEDs there was absolutely no response from the strips whereas UDPraw gave results but it was wrong.

I was just trying to help improve the documentation to make things easier on people going forward. If you want to doubt what I've tried to contribute then so be it. Was just trying to help.

If you prefer to not have clearer documentation to save others headaches then so be it.

**Comment by Lord-Grey** [comment]
> I was just trying to help improve the documentation to make things easier on people going forward. If you want to doubt what I've tried to contribute then so be it. Was just trying to help.
> 
> If you prefer to not have clearer documentation to save others headaches then so be it.

That is very much appreciated!
I was not trying to convince you differently, but wanted to better understand your challenges and have the documentation at the right place. Just putting a WLED receiver issue under UDP-Raw documentation might not help the Users starting from WLED

**Comment by houseofbugs** [comment]
This will likely affect other UDP integrations as its not really a WLED issue but just a limitation with the UDP datapacket size in general on networks.

**Comment by Lord-Grey** [comment]
You can execute fragmented packages via UDP.
Given that UDP Raw is not having any header or checksum (as other UDP protocols supported by Hyperion, e.g. E131, H801), there is the risk that the stream breaks, if there is a fragmented packe lost.
That is why (I suppose) WLED is limiting to one fragment. If one fragment is lost there is no harm, as the next stream update will come...
Let me think about to hardly limit the LED-Num for UDP-Raw or WLED.
Until now I was hesitant to give users the flexibility still using fragmented messages at their own risk.

**Comment by Lord-Grey** [comment]
@houseofbugs Besides the documentation update, please see the following PR, which takes care that a user will not be able configuring more than 490 LEDs for WLED or UDP-Raw.

https://github.com/hyperion-project/hyperion.ng/pull/1334

Feel free to test the PR and provide feedback.

**Pull request closed without merging**
