### PR TITLE
Update Installation.md

### PR DESCRIPTION
**Pull request by micha53**
Installation procedure proposal for existing Raspberry OS added 
(a 1st trial to give back something what I have received in terms of help ;-)

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
If you add a little visual enhancement to the text passages, it will be more readable. Thanks so far for your contribution to this project. 👍🏻

**Comment by micha53** [comment]
I don't know how to Check my result visually. I online made a copy of the Debian section and interchanged the Text.

**Comment by Paulchen-Panther** [comment]
> I don't know how to Check my result visually. I online made a copy of the Debian section and interchanged the Text.

The bot on netlifly creates a preview of your change:
https://github.com/hyperion-project/hyperion.docs/pull/6#issuecomment-841472155

**Comment by Paulchen-Panther** [comment]
@micha53 
@tpmodding is also working on the doc right now. Maybe it would be an advantage if you work together.

**Comment by Lord-Grey** [comment]
> I don't know how to Check my result visually. I online made a copy of the Debian section and interchanged the Text.

There are multiple Markdown (MD) editors available online.
A sample editor, you can find [here](https://dillinger.io/), but you might use others you find more convenient (just search for 
"markdown editor online".

Normally, you edit your MarkDown text on the left side and on the right you see the outcome.

**Comment by micha53** [comment]
Thanks, 
Pauchen-Panther gave me some usful hints some days ago.
Does anybody know a page where I can learn how to use GithubDesktop? Do I need it really?
The changes above I made directly in the fork on my Github account.

**Pull request merged**
